# virtual key codes - https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

# no whire spaces allowed
# ctrl+g
TVKeys=[0x11, 0x47]
# ctrl+c
PanicKey=[0x11, 0x43]
SpyCheck=true
SpyPanic=false
